#!/bin/bash
puppet resource package apache2 ensure=installed
puppet resource service apache2 ensure=running enable=true

rm -rf /operate/5010490y
mkdir -p /operate/5010490y

cd /operate/5010490y
git clone https://zaapiez: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@github.com/zaapiez/5010490y-op-repo.git .

cp /operate/5010490y/index-op-5010490y.html /var/www/html/index.html
